// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[lang]" | "/[lang]/dashboard" | "/[lang]/login" | "/[lang]/onboarding" | "/[lang]/signup"
type AppRouteHandlerRoutes = "/[lang]/auth/callback" | "/api/chat" | "/api/health" | "/api/meals" | "/api/meals/[id]" | "/api/meals/analytics" | "/api/meals/analyze" | "/api/meals/analyze-pantry" | "/api/meals/analyze-preview" | "/api/meals/feedback" | "/api/meals/pantry" | "/api/meals/pantry/[id]" | "/api/meals/pantry/suggest" | "/api/meals/recipes" | "/api/meals/today"
type PageRoutes = never
type LayoutRoutes = "/" | "/[lang]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[lang]": { "lang": string; }
  "/[lang]/auth/callback": { "lang": string; }
  "/[lang]/dashboard": { "lang": string; }
  "/[lang]/login": { "lang": string; }
  "/[lang]/onboarding": { "lang": string; }
  "/[lang]/signup": { "lang": string; }
  "/api/chat": {}
  "/api/health": {}
  "/api/meals": {}
  "/api/meals/[id]": { "id": string; }
  "/api/meals/analytics": {}
  "/api/meals/analyze": {}
  "/api/meals/analyze-pantry": {}
  "/api/meals/analyze-preview": {}
  "/api/meals/feedback": {}
  "/api/meals/pantry": {}
  "/api/meals/pantry/[id]": { "id": string; }
  "/api/meals/pantry/suggest": {}
  "/api/meals/recipes": {}
  "/api/meals/today": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[lang]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
