// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/[lang]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/login">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/signup">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[lang]/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/analytics">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/analyze-pantry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/analyze-pantry">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/analyze-pantry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/analyze-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/analyze-preview">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/analyze-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/analyze">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/feedback">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/pantry/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/pantry/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/pantry/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/pantry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/pantry">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/pantry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/pantry/suggest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/pantry/suggest">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/pantry/suggest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/recipes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/recipes">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/recipes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/meals/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meals/today">> = Specific
  const handler = {} as typeof import("../../../app/api/meals/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/[lang]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
